import type { IconSvgElement } from '@hugeicons/react'
import {
  Airplane01Icon,
  Globe02Icon,
  CompassIcon,
  BeachIcon,
  MountainIcon,
  Briefcase01Icon,
  Presentation01Icon,
  Target01Icon,
  UserGroupIcon,
  Calendar01Icon,
  BookOpen01Icon,
  GraduationScrollIcon,
  PenTool01Icon,
  Book01Icon,
  MusicNote01Icon,
  HeadphonesIcon,
  Film01Icon,
  Camera01Icon,
  GameIcon,
  PaintBoardIcon,
  Coffee01Icon,
  ShoppingBag01Icon,
  Dumbbell01Icon,
  Leaf01Icon,
  FlowerIcon,
  Sun01Icon,
  MoonIcon,
  StarIcon,
  Rocket01Icon,
  CodeIcon,
  GiftIcon,
  SmileIcon,
  MapPinIcon,
} from '@hugeicons/core-free-icons'

export const CATEGORY_ICONS: { key: string; label: string; icon: IconSvgElement }[] = [
  { key: 'airplane', label: 'Travel', icon: Airplane01Icon },
  { key: 'globe', label: 'World', icon: Globe02Icon },
  { key: 'compass', label: 'Explore', icon: CompassIcon },
  { key: 'beach', label: 'Beach', icon: BeachIcon },
  { key: 'mountain', label: 'Nature', icon: MountainIcon },
  { key: 'briefcase', label: 'Work', icon: Briefcase01Icon },
  { key: 'presentation', label: 'Meeting', icon: Presentation01Icon },
  { key: 'target', label: 'Goals', icon: Target01Icon },
  { key: 'userGroup', label: 'Team', icon: UserGroupIcon },
  { key: 'calendar', label: 'Schedule', icon: Calendar01Icon },
  { key: 'bookOpen', label: 'Study', icon: BookOpen01Icon },
  { key: 'graduation', label: 'Education', icon: GraduationScrollIcon },
  { key: 'penTool', label: 'Writing', icon: PenTool01Icon },
  { key: 'book', label: 'Reading', icon: Book01Icon },
  { key: 'musicNote', label: 'Music', icon: MusicNote01Icon },
  { key: 'headphones', label: 'Audio', icon: HeadphonesIcon },
  { key: 'film', label: 'Film', icon: Film01Icon },
  { key: 'camera', label: 'Photo', icon: Camera01Icon },
  { key: 'game', label: 'Gaming', icon: GameIcon },
  { key: 'paintBoard', label: 'Art', icon: PaintBoardIcon },
  { key: 'coffee', label: 'Café', icon: Coffee01Icon },
  { key: 'shopping', label: 'Shopping', icon: ShoppingBag01Icon },
  { key: 'dumbbell', label: 'Fitness', icon: Dumbbell01Icon },
  { key: 'leaf', label: 'Wellness', icon: Leaf01Icon },
  { key: 'flower', label: 'Garden', icon: FlowerIcon },
  { key: 'sun', label: 'Day', icon: Sun01Icon },
  { key: 'moon', label: 'Night', icon: MoonIcon },
  { key: 'star', label: 'Favorite', icon: StarIcon },
  { key: 'rocket', label: 'Launch', icon: Rocket01Icon },
  { key: 'code', label: 'Code', icon: CodeIcon },
  { key: 'gift', label: 'Gift', icon: GiftIcon },
  { key: 'smile', label: 'Mood', icon: SmileIcon },
  { key: 'mapPin', label: 'Location', icon: MapPinIcon },
]

export const CATEGORY_ICON_MAP: Record<string, IconSvgElement> = {}
for (const entry of CATEGORY_ICONS) {
  CATEGORY_ICON_MAP[entry.key] = entry.icon
}
